# Generated by Django 5.2 on 2025-05-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_question_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="updated_at",
            new_name="updated_date",
        ),
    ]
